config/routes.rb
Rails.application.routes.draw do
  root to: 'time_clock#index'

  resources :teachers, only: [:create]
  resources :time_cards
  resources :time_clock do
    collection do
      get :clock_in
      get :clock_out
      get :ticker
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/teacher.rb
class Teacher < ApplicationRecord
  # My form can references these constants in order to limit the length of the input.
  MIN_NAME_LENGTH = 3
  MAX_NAME_LENGTH = 50

  has_many :time_cards

  validates :name, presence: true, uniqueness: true, length: { minimum: MIN_NAME_LENGTH, maximum: MAX_NAME_LENGTH }
end

app/models/time_card.rb
class TimeCard < ApplicationRecord
  belongs_to :teacher, optional: false

  validates :started_at, presence: true
  validate :end_date_after_start_date, if: -> { ended_at.present? }

  delegate :name, to: :teacher, prefix: true

  scope :active, -> {
    where(ended_at: nil)
      .order(id: :desc)
  }

  private def end_date_after_start_date
    if ended_at < started_at
      errors.add :end_date, 'must be after start date'
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :check_if_active_time_card

  # Fetching records on every request leads to poor performance. But good enough for this prototype.
  def check_if_active_time_card
    if TimeCard.active.exists?
      flash[:info] = "You're already clocked in. Clock out to use other features."
      redirect_to ticker_time_clock_index_path
    end
  end
end

app/controllers/teachers_controller.rb
class TeachersController < ApplicationController
  def create
    teacher = Teacher.find_by(name: teacher_params[:name])

    if teacher
      redirect_to clock_in_time_clock_index_path({ teacher_id: teacher.id })
      return
    end

    teacher = Teacher.new(teacher_params)

    if teacher.save
      redirect_to clock_in_time_clock_index_path({ teacher_id: teacher.id })
      return
    end

    flash[:error] = teacher.errors.full_messages.join(' ')
    redirect_to root_path
  end

  def teacher_params
    params.require(:teacher).permit(:name)
  end
end

app/controllers/time_cards_controller.rb
class TimeCardsController < ApplicationController
  before_action :set_time_card, only: [:show, :edit, :update, :destroy]

  def index
    @time_cards = TimeCard.includes(:teacher).all
  end

  def edit
  end

  def update
    if @time_card.update(time_card_params)
      redirect_to time_cards_path, notice: 'Time card was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @time_card.destroy
    redirect_to time_cards_path, notice: 'Time card was successfully destroyed.'
  end

  # Use callbacks to share common setup or constraints between actions.
  private def set_time_card
    @time_card = TimeCard.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  private def time_card_params
    params.require(:time_card).permit(:started_at, :ended_at, :teacher)
  end
end

app/controllers/time_clock_controller.rb
class TimeClockController < ApplicationController
  # Skip before action can lead to spaghetti callbacks. However in a small prototype
  # this can quickly implement global behaviour.
  skip_before_action :check_if_active_time_card, only: [:ticker, :clock_out]

  def index
    @teacher = Teacher.new

    # Provided simple bounds. Never return "all results". Pagination
    # and a flexible limit should be used. Saving time by setting a fixed limit.
    @teachers = Teacher.all.order(name: :asc).limit(50)
  end

  def clock_in
    teacher = Teacher.find(params[:teacher_id])

    TimeCard.create!(teacher: teacher, started_at: Time.now)

    redirect_to ticker_time_clock_index_path
  end

  def ticker
    @time_card = TimeCard.includes(:teacher).active.first
  end

  def clock_out
    time_card = TimeCard.find(params[:time_card_id])
    time_card.update!(ended_at: Time.now)

    redirect_to root_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title Clocker
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'

    -# Remote assets are not ideal, but are faster for prototypes like this.
    %link{crossorigin: "anonymous", href: "https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css", integrity: "sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T", rel: "stylesheet"}/

  %body
    %nav.navbar.navbar-expand-lg.navbar-dark.bg-dark.mb-3
      %span.navbar-brand Clocker
      %ul.navbar-nav
        %li.nav-item
          = link_to 'Clock In', root_path, class: 'nav-link'
        %li.nav-item
          = link_to 'Time Cards', time_cards_path, class: 'nav-link'

    .container-fluid
      - if flash.any?
        .row
          .col
            .alert.alert-info
              - flash.each do |type, msg|
                = [type.titleize, msg].join(': ')
      .row
        .col
          = yield

app/views/time_cards/_form.html.haml
= simple_form_for @time_card do |f|
  - if @time_card.errors.any?
    #error_explanation
      %h2= "#{pluralize(@time_card.errors.count, "error")} prohibited this time_card from being saved:"
      %ul
        - @time_card.errors.full_messages.each do |message|
          %li= message

  = f.input :teacher_name, readonly: true, disabled: true
  = f.input :started_at, html5: true, required: true
  = f.input :ended_at, html5: true
  = f.button :submit, class: 'btn btn-primary'

app/views/time_cards/edit.html.haml
%h2.pb-2.mb-3.border-bottom Time Card

= simple_form_for @time_card do |f|
  - if @time_card.errors.any?
    .alert.alert-danger
      %h5 Some errors happened:
      - @time_card.errors.full_messages.each do |message|
        %div= '- ' + message

  = f.input :teacher_name, readonly: true, disabled: true
  = f.input :started_at, html5: true, required: true
  = f.input :ended_at, html5: true
  = f.button :submit, class: 'btn btn-secondary'

  = link_to 'Cancel', time_cards_path, class: 'btn btn-light border'

app/views/time_cards/index.html.haml
%table.table.table-bordered.table-sm
  %thead.thead-light
    %tr
      %th Teacher
      %th Started at
      %th Ended at
      %th{colspan: 2}

  %tbody
    - @time_cards.each do |time_card|
      %tr
        %td= time_card.teacher.name
        %td= time_card.started_at
        %td= time_card.ended_at
        %td= link_to 'Edit', edit_time_card_path(time_card)
        %td= link_to 'Destroy', time_card, method: :delete, data: { confirm: 'Are you sure?' }

app/views/time_clock/index.html.haml
.row.mb-5
  .col
    %h5 New teacher? Add yourself to the list.

    = simple_form_for @teacher, url: teachers_path do |f|
      -# Could use HTML5 validation, but I want to implement flash messages.
      = f.input :name, label: false, placeholder: 'Your name', maxlength: Teacher::MAX_NAME_LENGTH
      = f.submit 'Sign Up & Clock In', class: 'btn btn-dark'
.row
  .col
    %h5 Existing teacher? Find your account.
    - @teachers.each do |teacher|
      .card.p-2.mb-3.bg-light.flex-row.align-items-center
        = teacher.name
        = link_to 'Clock In', clock_in_time_clock_index_path(teacher_id: Teacher.last.id), class: 'ml-auto btn btn-sm btn-secondary'

app/views/time_clock/ticker.html.haml
.text-center
  %div.mb-5
    %h1= @time_card.teacher_name
  %div.mb-5
    %div
      %small
        %em Clocked In At
    = @time_card.started_at
  %div
    = link_to 'Clock Out', clock_out_time_clock_index_path(time_card_id: @time_card.id), class: 'btn btn-secondary'